In [1]:
import numpy as np  ## shift + enter

In [2]:
arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]])
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]]])

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
arr3

In [ ]:
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


In [ ]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(8,)
(5, 3)
(1, 5, 3)


In [ ]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
len(arr1)

8

In [ ]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 4,  3, 10],
       [44, 33, 22]])

In [ ]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 4,  3, 10],
        [44, 33, 22]]])

In [ ]:
arr3.shape

(1, 5, 3)

In [ ]:
arr4 = np.array([[[1,2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]],
                 [[1,2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]],
                 [[1,2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]]])

In [ ]:
arr4.ndim

In [ ]:
arr4.shape

In [ ]:
len(arr4)

In [ ]:
len(arr3)

In [ ]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 4,  3, 10],
       [44, 33, 22]])

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr4 = np.array([[1.4,2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]])
arr4

In [ ]:
arr4.dtype

In [ ]:
arr5 = np.array([['Umang',2,3],[4,5,6],[7,8,9],[4,3,10],[44,33,22]])
arr5

In [ ]:
arr5.dtype

In [ ]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 4,  3, 10],
       [44, 33, 22]])

In [ ]:
np.max(arr2)
## arr2.max()

In [ ]:
np.min(arr2)

In [3]:
np.argmax(arr2)

12

In [ ]:
np.argmin(arr2)

In [ ]:
arr2

In [ ]:
np.mean(arr2)

10.733333333333333

In [ ]:
np.round(np.mean(arr2))

In [ ]:
np.round(np.mean(arr2),2)

In [ ]:
np.sum(arr2)

161

In [ ]:
np.sum(arr2,axis=0)  ## column wise add

array([60, 51, 50])

In [ ]:
np.sum(arr2,axis=1)  ## row wise add

array([ 6, 15, 24, 17, 99])

In [ ]:
#### Array Slicing (Picking Elements from the array)

In [ ]:
arr2 = np.array([[1,2,3,4,5,6],[4,5,6,2,4,5],[7,8,9,1,3,43]
                 ,[4,3,10,2,2,2],[44,33,22,2,2,1]])
arr2

In [ ]:
arr2[3]

array([ 4,  3, 10,  2,  2,  2])

In [ ]:
arr2[:]  ### all rows

In [ ]:
arr2[1:4]  ## index 1-3

In [ ]:
arr2[1:]  ## index 1 to last

In [ ]:
arr2[:4]  ## index 0 to 3

In [ ]:
arr2[:,:]  ## all rows and all cols (row,coln)

array([[ 1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  2,  4,  5],
       [ 7,  8,  9,  1,  3, 43],
       [ 4,  3, 10,  2,  2,  2],
       [44, 33, 22,  2,  2,  1]])

In [ ]:
arr2[1:4,1:4]  ## row - 1,2,3  coln - 1,2,3

array([[ 5,  6,  2],
       [ 8,  9,  1],
       [ 3, 10,  2]])

In [ ]:
arr2[1:4,3]   ## coln 3 of row 1,2,3

In [ ]:
arr2[1:5]   ## row 1-4

In [ ]:
arr2[1:5:2]  ## 1,3

array([[ 4,  5,  6,  2,  4,  5],
       [ 4,  3, 10,  2,  2,  2]])

In [ ]:
arr2[1:5:3]  ## 1,4 

array([[ 4,  5,  6,  2,  4,  5],
       [44, 33, 22,  2,  2,  1]])

In [ ]:
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 4,  5,  6,  2,  4,  5],
       [ 7,  8,  9,  1,  3, 43],
       [ 4,  3, 10,  2,  2,  2],
       [44, 33, 22,  2,  2,  1]])

In [ ]:
arr2[2,2]

9

In [ ]:
### Linspace Function - generate equidistant numbers b/w a range (3,6,9,12)
np.linspace(start=5,stop=100,num=20)

array([  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
        60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [ ]:
a = np.linspace(start=5,stop=100,num=10)
a

array([  5.        ,  15.55555556,  26.11111111,  36.66666667,
        47.22222222,  57.77777778,  68.33333333,  78.88888889,
        89.44444444, 100.        ])

In [ ]:
b = np.linspace(start=5,stop=100,num=10,retstep=True)
b

(array([  5.        ,  15.55555556,  26.11111111,  36.66666667,
         47.22222222,  57.77777778,  68.33333333,  78.88888889,
         89.44444444, 100.        ]), 10.555555555555555)

In [ ]:
type(a)

In [ ]:
type(b)

tuple

In [ ]:
a[1]

In [ ]:
b[1]

In [ ]:
b[0][1]

In [ ]:
np.linspace(start=5,stop=100,num=10,endpoint=False,retstep=True)

(array([ 5. , 14.5, 24. , 33.5, 43. , 52.5, 62. , 71.5, 81. , 90.5]), 9.5)

In [ ]:
np.linspace(5,100,10,endpoint=False,retstep=True)

(array([ 5. , 14.5, 24. , 33.5, 43. , 52.5, 62. , 71.5, 81. , 90.5]), 9.5)

In [ ]:
np.linspace(endpoint=False,retstep=True,start=5,stop=100,num=10)

(array([ 5. , 14.5, 24. , 33.5, 43. , 52.5, 62. , 71.5, 81. , 90.5]), 9.5)

In [ ]:
### Arange Function

In [ ]:
np.arange(5,100,2.5)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. , 27.5, 30. ,
       32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5, 50. , 52.5, 55. , 57.5,
       60. , 62.5, 65. , 67.5, 70. , 72.5, 75. , 77.5, 80. , 82.5, 85. ,
       87.5, 90. , 92.5, 95. , 97.5])

In [ ]:
len(np.arange(5,100,2.5))

In [ ]:
np.arange(5,100.1,2.5)

array([  5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,  25. ,
        27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,  45. ,  47.5,
        50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,
        72.5,  75. ,  77.5,  80. ,  82.5,  85. ,  87.5,  90. ,  92.5,
        95. ,  97.5, 100. ])

In [ ]:
### Change shape or dimension of array
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1.shape

In [ ]:
## Change to 2d array -- (2,4),(4,2),(8,1),(1,8)
arr_1 = arr1.reshape(4,2)
arr_1

In [ ]:
## Change to 3d array -- (2,2,2),(1,4,2),(1,2,4),(1,8,1)
arr_2 = arr1.reshape(2,2,2)
arr_2

In [ ]:
### Random Numbers

In [ ]:
np.random.randint(100)  ## 0-99

70

In [ ]:
np.random.seed(1)   ### range of seed (0 - 2^32 - 1)
np.random.randint(100)

In [ ]:
np.random.seed(4294967290)
np.random.randint(100)

In [ ]:
2**32

4294967296

In [ ]:
np.random.randint(100,800)  ### 100-799

In [ ]:
np.random.randint(100,900,30) ## 30 samples

In [ ]:
np.random.randint(100,900,(4,5))

In [ ]:
np.random.randint(100,900,(3,2,4))

array([[[310, 367, 424, 793],
        [880, 491, 814, 100]],

       [[563, 364, 514, 701],
        [333, 346, 282, 789]],

       [[254, 448, 347, 607],
        [698, 430, 842, 185]]])

In [ ]:
np.random.random(10)

array([0.43995925, 0.73773692, 0.4742127 , 0.64633891, 0.48262597,
       0.05033005, 0.66358518, 0.93683074, 0.90445344, 0.86641965])

In [ ]:
### Standard Matrix (Zero, Ones, Identity)

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])