In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_csv("/content/Salary_Data.csv")
data.head()

In [ ]:
data.info()

In [ ]:
data.isnull().sum()

In [ ]:
data.head()

In [9]:
len(data)

30

In [ ]:
### Shape of Feature should always be (num.of samples,no.of features) -- 2D Array
### Shape of Target should always be either (no.of samples,) or (no.of samples,no.of targets) -- 1d or 2D

In [ ]:
### Shape of feature - (30,1)
### Shape of target - (30,) or (30,1)

In [ ]:
### Divide the data into features(ip) and target(op)
x = data['YearsExperience'].values
x

In [ ]:
x = x.reshape(len(data),1)
x.shape

In [ ]:
y = data['Salary'].values
y

In [ ]:
y.shape

In [41]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=200)

In [ ]:
xtest

In [43]:
#### Build the model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [44]:
### Perform Training 
model.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [45]:
### Prediction
ypred = model.predict(xtest)
ypred

array([108335.56338618, 125509.79795421,  39638.62511404, 100702.57024483,
        35822.12854337,  81620.08739146])

In [46]:
xtest

array([[ 8.7],
       [10.5],
       [ 1.5],
       [ 7.9],
       [ 1.1],
       [ 5.9]])

In [47]:
ytest

array([109431., 121872.,  37731., 101302.,  39343.,  81363.])

In [ ]:
### R2 Score
from sklearn.metrics import r2_score
r2 = r2_score(ytest,ypred)
r2*100

In [ ]:
#### Line of Regression (Training Samples)
plt.scatter(xtrain,ytrain,color="red",label="Actual Points")
plt.scatter(xtrain,model.predict(xtrain),color="blue",label="Predicted Points")
plt.plot(xtrain,model.predict(xtrain),color="orange",label="Line of Regression")
plt.legend()
plt.show()

In [ ]:
#### Line of Regression (Testing Samples)
plt.scatter(xtest,ytest,color="red",label="Actual Points")
plt.scatter(xtest,model.predict(xtest),color="blue",label="Predicted Points")
plt.plot(xtest,model.predict(xtest),color="orange",label="Line of Regression")
plt.legend()
plt.show()

In [32]:
m = model.coef_   ## slope
c = model.intercept_   ## y intercept

In [33]:
print(m,c)

[9312.57512673] 26780.09915062818


In [34]:
## y = 9312.5 * x + 26780   --- Equation of Line

In [35]:
m * 10.1 + c  ## salary for 10.1

array([120837.10793059])

In [36]:
model.predict([[10.1]])

array([120837.10793059])

In [37]:
score = []
for i in range(501):
  xtrain_1,xtest_1,ytrain_1,ytest_1 = train_test_split(x,y,train_size=0.8,random_state=i)
  model_1 = LinearRegression()
  model_1.fit(xtrain_1,ytrain_1)
  ypred_1 = model_1.predict(xtest_1)
  r2_new = r2_score(ytest_1,ypred_1)
  score.append(r2_new)

In [ ]:
score

In [ ]:
np.max(score)

In [ ]:
np.argmax(score)

In [ ]:
### Saving the Model In a file
import joblib
joblib.dump(model,"umang_salary_regression_model.pkl")

In [54]:
### Load the model
mymodel = joblib.load("/content/umang_salary_regression_model.pkl")

In [55]:
mymodel.predict([[22]])

array([235234.07436109])

In [60]:
def salary_predict():
  years = float(input("Enter Work Experience in Years : "))
  salary = mymodel.predict([[years]])
  salary = round(salary[0],2)
  print("The predicted salary is "+str(salary))

In [61]:
salary_predict()

Enter Work Experience in Years : 9
The predicted salary is 111197.94
